# -*- coding: utf-8 -*-
"""HW2_hash_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojk2H7gM1DWaJmU1rI47cLe8GGetfZq3
"""

import matplotlib.pyplot as plt

word_counts = dict()

with open("hw2_data.txt", "r") as file:
    for line in file:
        word = line.strip()
        if word:#檢查空白
            if word in word_counts:
                word_counts[word] += 1
            else:
                word_counts[word] = 1

#1.印出不重複的單字數量
print(f"1.總共有 {len(word_counts)} 個不重複的英文字")

#2.印出每個字出現的次數（從多到少排序）
sorted_items = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)
print("2.每個英文字出現的次數：")
for word, count in sorted_items:
    print(f"{word}: {count}")

#3.畫圖
plt.figure(figsize=(12, 6))
plt.bar([w for w, _ in sorted_items], [c for _, c in sorted_items])
plt.xticks(rotation=90)
plt.xlabel("English Words")
plt.ylabel("Frequency")
plt.title("Histogram")
plt.tight_layout()
plt.show()